# Настройки плагина
plugin:
  pvpIsAlwaysAllowedInTheseWorlds:
    - world_the_end
  raid:
    # Задержка перед началом рейда (в минутах)
    delay: 15
    # Требуемое количество сломанных блоков обсидиана в Нексусе
    requiredDestroyCount: 10
    # Длительность рейда
    durationMinutes: 1
    # Длительность ожидания игроков для присоединения к рейду
    openDurationMinutes: 10
    # Разница в количестве игроков для начала рейдов
    differencePlayersCount: 2
    # Минимальное количество игроков в команде для начала
    minPlayers: 2
    # Количество минут щита после рейда
    shieldMinutes: 10
    # Количество минут щита атакующей команды после рейда
    shieldMinutesDefending: 1
    # Включена ли система рейдов или нет
    isEnabled: false
    # Перезарядка команды /setraidbase
    setRaidBaseCooldown: 1
    # Перезарядка команды /sethomebase
    setHomeBaseCooldown: 1
    # Радиус региона привата базы для рейда
    privateRadiusRaid: 10
    # Радиус региона привата дома
    privateRadiusHome: 10
    # Радиус главного острова в Энде
    endWorldMainIslandRadius: 150
    # После рейда разрешено PvP и взаимодействия ещё N минут
    minutesPrivateDelayAfterRaid: 5

dragon:
  respawnIntervalHours: 6

# Настройки команд и командных блоков
teams:
  # Команда "red"
  RED:
    # Капитан команды
    captain: "RedCaptain"
    # Члены команды
    members:
      - "RedPlayer1"
      - "RedPlayer2"
  # Команда "blue"
  BLUE:
    # Капитан команды
    captain: "BlueCaptain"
    # Члены команды
    members:
      - "BluePlayer1"
      - "BluePlayer2"